### ISSUE TITLE
Missing "bg" for player.male and female.

### ISSUE THREAD

**Issue by AndrXi** [Zetsukaze/Zets-Hair-Extensions#1]
The mod seems to work without a problem if only for the lack of the background "shadow" that the tileset has by default.
I dug around the tile_config.json from MSX++ DeadPeople and it seems to call for the "fg" and "bg" of the player_male and female, but your mod_tileset.json calls from your bodies.png which does not have the "bg" that the tileset has.
I'm not sure if this is what is causing the issue or if I missed something obvious during installation.
Hopefully it's a just a mistake on my end.

**Comment by Zetsukaze** [comment]
Hmm, I got the .png directly from SomeDeadGuy, so not too sure what I'm missing here. Thanks! I'll check with him and see if there is anything to fix :)

**Comment by AndrXi** [comment]
I appreciate it , sorry I couldn't be more specific with the issue.

**Comment by Zetsukaze** [comment]
Fixed, thanks for noticing!
