### ISSUE TITLE
Cata++ Patch request

### ISSUE THREAD

**Issue by Noctifer-de-Mortem** [Zetsukaze/Zets-Hair-Extensions#2]
Hello, so there is the cata++ patch for this mod, which I am grateful for to edit the NPCs of the mod, but I included my own version of the patch with cata++. Reason being is that it will allow me to customize new NPCs as I add them or edit old ones easily without having to pester the maintainers here. May I ask that the patch included here with cata++ be removed so that there are no compatibility issues?

**Comment by Zetsukaze** [comment]
Sure, that's excellent! I'll remove it :)

**Comment by Zetsukaze** [comment]
Closed with commit dafe7a0af2e2719706bc4185914d448bc85faef3
